version: '3.3'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
  flask:
    build: .
    volumes:
      - ${PWD}/example:/example
    ports:
      - "8080:8080"
